# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j3EAkp33LUY9cjuH2-TXmWEagat-HiMk
"""

pip install pandas matplotlib

import pandas as pd

# Membaca file CSV dan membuat DataFrame
df = pd.read_csv('movies.csv')

# Menampilkan DataFrame
print(df)

import pandas as pd
import plotly.express as px

# Membaca file CSV
df = pd.read_csv('movies.csv')

# Membuat visualisasi interaktif menggunakan Plotly Express
fig = px.scatter(df, x='title', y='genres', title='Hubungan Title dan Genre')

fig.show()

import pandas as pd
import plotly.express as px

# Membaca file CSV
df = pd.read_csv('movies.csv')

# Membuat visualisasi interaktif menggunakan Plotly Express
fig = px.scatter(df, x='title', y='genres', title='Hubungan Title dan Genre', color='title', hover_data=['movieId'])

# Menambahkan slider
fig.update_layout(
    xaxis=dict(
        rangeslider=dict(
            visible=True
        ),
        type="date"
    )
)

# Menambahkan select dropdown
fig.update_layout(
    updatemenus=[
        dict(
            buttons=list([
                dict(
                    args=[{'marker.color': 'red'}],
                    label='Red',
                    method='update'
                ),
                dict(
                    args=[{'marker.color': 'blue'}],
                    label='Blue',
                    method='update'
                ),
                dict(
                    args=[{'marker.color': 'green'}],
                    label='Green',
                    method='update'
                )
            ]),
            direction='down',
            showactive=True,
            x=0.1,
            xanchor='left',
            y=1.2,
            yanchor='top'
        )
    ]
)

fig.show()